name: Publish VSCode Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.15.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish to VSCode Marketplace
        run: |
          npm run deploy
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
